# Generated by Django 5.2.12 on 2026-03-07 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('short_description', models.CharField(max_length=255)),
                ('full_description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='locations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price_rub', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('is_demo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AudioGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='ru', max_length=16)),
                ('voice_name', models.CharField(blank=True, max_length=80)),
                ('audio_file', models.FileField(upload_to='audio_guides/')),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('source_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio_guide', to='guides.location')),
            ],
        ),
    ]
