# Generated by Django 5.2.12 on 2026-03-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0002_userprofile_favoritelocation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-is_featured', 'title']},
        ),
        migrations.AddField(
            model_name='location',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
