# Generated by Django 5.2.12 on 2026-03-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0003_alter_location_options_location_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioguide',
            name='acquisition_channel',
            field=models.CharField(choices=[('site', 'Сайт StoryWalk'), ('email', 'Email-рассылка'), ('social', 'Соцсети'), ('thematic', 'Тематические каналы')], default='site', help_text='Канал из Lean Canvas, через который пользователь пришёл к этому гиду.', max_length=16, verbose_name='Основной канал привлечения'),
        ),
        migrations.AddField(
            model_name='location',
            name='access_level',
            field=models.CharField(choices=[('free', 'Базовый (бесплатно)'), ('paid', 'Расширенный (по подписке)')], default='free', help_text='Логика фримиум: базовые гиды бесплатно, расширенные — по подписке.', max_length=8, verbose_name='Уровень доступа'),
        ),
        migrations.AddField(
            model_name='location',
            name='segment',
            field=models.CharField(choices=[('solo', 'Самостоятельные путешественники'), ('family', 'Семьи и пары'), ('mixed', 'Смешанный сегмент')], default='solo', help_text='Сегмент из Lean Canvas: кто чаще всего слушает этот гид.', max_length=16, verbose_name='Целевой сегмент'),
        ),
        migrations.AlterField(
            model_name='audioguide',
            name='audio_file',
            field=models.FileField(upload_to='audio_guides/', verbose_name='Аудиофайл (mp3)'),
        ),
        migrations.AlterField(
            model_name='audioguide',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='Длительность (сек.)'),
        ),
        migrations.AlterField(
            model_name='audioguide',
            name='language',
            field=models.CharField(default='ru', max_length=16, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='audioguide',
            name='source_url',
            field=models.URLField(blank=True, verbose_name='Источник текста'),
        ),
        migrations.AlterField(
            model_name='audioguide',
            name='voice_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Голос ИИ'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=120, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='location',
            name='full_description',
            field=models.TextField(verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='locations/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='location',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Фича/рекомендация'),
        ),
        migrations.AlterField(
            model_name='location',
            name='short_description',
            field=models.CharField(max_length=255, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='location',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название локации'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='is_demo',
            field=models.BooleanField(default=True, verbose_name='Демо-тариф'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Название тарифа'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price_rub',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена в месяц (₽)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=240, verbose_name='Коротко о себе'),
        ),
    ]
