# Generated by Django 5.2.12 on 2026-04-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0005_audiolistenevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioguide',
            name='audio_long_file',
            field=models.FileField(blank=True, null=True, upload_to='audio_guides/', verbose_name='Длинная версия (mp3)'),
        ),
        migrations.AddField(
            model_name='audioguide',
            name='audio_short_file',
            field=models.FileField(blank=True, null=True, upload_to='audio_guides/', verbose_name='Короткая версия (mp3)'),
        ),
    ]
