# Generated by Django 5.2.12 on 2026-04-04 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0006_audioguide_audio_long_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='locations/gallery/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=140, verbose_name='Подпись')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='guides.location')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
