# Generated by Django 5.2.12 on 2026-09-03 11:36

import django.core.validators
from django.conf import settings
from django.db import migrations, models


def normalize_release_state(apps, schema_editor):
    Location = apps.get_model('guides', 'Location')
    WalkRoute = apps.get_model('guides', 'WalkRoute')

    Location.objects.filter(is_published=True).exclude(
        content_status='published',
    ).update(is_published=False)
    WalkRoute.objects.filter(is_published=True).exclude(
        routing_status='verified',
    ).update(is_published=False)

    legacy = Location.objects.filter(title='Эритаж').first()
    if legacy and not Location.objects.filter(title='Эрмитаж').exists():
        legacy.title = 'Эрмитаж'
        legacy.save(update_fields=['title'])


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0014_route_routing_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="audiolistenevent",
            name="audio_variant",
            field=models.CharField(
                choices=[
                    ("short", "Короткая история"),
                    ("long", "Полная история"),
                    ("route", "История в маршруте"),
                    ("legacy", "Аудио без версии"),
                ],
                default="legacy",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="audiolistenevent",
            name="session_id",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="audiolistenevent",
            name="completion_percent",
            field=models.FloatField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="audiolistenevent",
            name="current_seconds",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="audiolistenevent",
            name="duration_seconds",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-90),
                    django.core.validators.MaxValueValidator(90),
                ],
                verbose_name="Широта",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                ],
                verbose_name="Долгота",
            ),
        ),
        migrations.AlterField(
            model_name="routestop",
            name="position",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Номер остановки",
            ),
        ),
        migrations.AddIndex(
            model_name="audiolistenevent",
            index=models.Index(
                fields=["location", "event_type", "-created_at"],
                name="audio_event_lookup_idx",
            ),
        ),
        migrations.RunPython(normalize_release_state, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_published", False),
                    ("content_status", "published"),
                    _connector="OR",
                ),
                name="published_location_has_published_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="walkroute",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_published", False),
                    ("routing_status", "verified"),
                    _connector="OR",
                ),
                name="published_route_is_verified",
            ),
        ),
    ]
